// `zenkit-nodekit`: the Node-side half of a pack's tooling.
//
//   zenkit-nodekit sync [--check]   write (or verify) the vendored Python package from pack.json
//   zenkit-nodekit check-widgets    every Python widget type has its frontend/widgets/*.vue, and back
//
// Run from the pack root (or pass --root). The Python half of nodekit lives in ../python as plain
// modules; sync copies them into the pack with a generated `identity.py`, so the Python side reads
// pack.json too (at sync time) and never spells the namespace out again.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

import { makeIdentity, type PackManifest } from '../src/identity'

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url))
// Built to dist/cli.js, so the package root is one level up.
const PKG_ROOT = here('..')
const TEMPLATES = join(PKG_ROOT, 'python')
const VERSION = (
  JSON.parse(readFileSync(join(PKG_ROOT, 'package.json'), 'utf8')) as { version: string }
).version

/** Every module of the vendored package. identity.py is generated; the rest are ../python copies. */
const MODULES = [
  'identity.py',
  '__init__.py',
  'io_types.py',
  'autodiscover.py',
  'media_api.py',
  'jobs.py',
  'server.py',
]
const MARKER = 'Generated by `zenkit-nodekit sync`'

class UsageError extends Error {}

interface PythonConfig {
  package: string
  vendor: string
  routes: string[]
  logPrefix: string
  widgets: string
}

const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/
const DOTTED = /^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$/

function str(v: unknown, field: string, fallback?: string): string {
  if (v === undefined && fallback !== undefined) return fallback
  if (typeof v !== 'string' || !v)
    throw new UsageError(`pack.json: "${field}" must be a non-empty string.`)
  return v
}

function readPack(root: string): { manifest: PackManifest; python: PythonConfig } {
  const file = join(root, 'pack.json')
  if (!existsSync(file))
    throw new UsageError(`No pack.json in ${root}. Run from the pack root or pass --root.`)
  const raw = JSON.parse(readFileSync(file, 'utf8')) as Record<string, unknown>
  const manifest: PackManifest = {
    namespace: str(raw.namespace, 'namespace'),
    displayName: str(raw.displayName, 'displayName'),
    category: str(raw.category, 'category'),
  }
  if (!/^[A-Za-z][A-Za-z0-9_.-]*$/.test(manifest.namespace))
    throw new UsageError(`pack.json: "namespace" must be letters, digits, ".", "-" or "_".`)
  const py = (raw.python ?? {}) as Record<string, unknown>
  if (typeof py !== 'object' || Array.isArray(py))
    throw new UsageError('pack.json: "python" must be an object.')
  const python: PythonConfig = {
    package: str(py.package, 'python.package', 'nodes'),
    vendor: str(py.vendor, 'python.vendor', '_zenkit'),
    routes: (py.routes ?? []) as string[],
    logPrefix: str(py.logPrefix, 'python.logPrefix', `[${manifest.displayName}]`),
    widgets: str(py.widgets, 'python.widgets', 'frontend/widgets'),
  }
  // A leading underscore keeps autodiscovery out of it, as it does for every helper module.
  if (!IDENT.test(python.vendor) || !python.vendor.startsWith('_'))
    throw new UsageError('pack.json: "python.vendor" must be a Python name starting with "_".')
  if (
    !Array.isArray(python.routes) ||
    python.routes.some((m) => typeof m !== 'string' || !DOTTED.test(m))
  )
    throw new UsageError(
      'pack.json: "python.routes" must be a list of module names, relative to python.package.',
    )
  return { manifest, python }
}

/** A Python string literal. JSON's escapes are all valid Python. */
const pyStr = (s: string) => JSON.stringify(s)

function header(): string {
  return (
    `# ${MARKER} (@nynxz/zenkit-nodekit ${VERSION}) from pack.json.\n` +
    `# Do not edit: change pack.json (or upgrade nodekit) and run \`zenkit-nodekit sync\` again.\n`
  )
}

function identityModule(manifest: PackManifest, python: PythonConfig): string {
  const id = makeIdentity(manifest)
  const prefix = id.typeId('')
  // As `ruff format` writes a tuple: `()`, `("a",)`, `("a", "b")`.
  const routes =
    python.routes.map((m) => pyStr(m)).join(', ') + (python.routes.length === 1 ? ',' : '')
  return `${header()}"""The pack's identity, from pack.json. The Python twin of nodekit's createNodekit()."""

from __future__ import annotations

import re

__all__ = [
    "CATEGORY",
    "DISPLAY_NAME",
    "LOG_PREFIX",
    "NAMESPACE",
    "NODEKIT_VERSION",
    "ROUTE_MODULES",
    "ROUTE_PREFIX",
    "WIDGET_IO_PREFIX",
    "node_id",
    "route",
    "setting_id",
    "type_id",
]

NAMESPACE = ${pyStr(id.NAMESPACE)}
DISPLAY_NAME = ${pyStr(id.DISPLAY_NAME)}
CATEGORY = ${pyStr(id.CATEGORY)}
#: Every HTTP route of the pack sits under this.
ROUTE_PREFIX = ${pyStr(id.ROUTE_PREFIX)}
#: Start of every widget io type: "LoraStack" -> ${pyStr(id.typeId('LoraStack'))}.
WIDGET_IO_PREFIX = ${pyStr(prefix)}
LOG_PREFIX = ${pyStr(python.logPrefix)}
#: The pack's own route modules (pack.json python.routes), imported by setup().
ROUTE_MODULES: tuple[str, ...] = (${routes})
NODEKIT_VERSION = ${pyStr(VERSION)}


def node_id(name: str) -> str:
    """Fully-qualified node_id: "Image.Compare" -> ${pyStr(id.nodeId('Image.Compare'))}."""
    return f"{NAMESPACE}.{name}"


def type_id(name: str) -> str:
    """Namespaced widget io type, nodekit's typeId(): "LoraStack" and "LORA_STACK" both give
    ${pyStr(id.typeId('LoraStack'))}."""
    snake = re.sub(r"([a-z0-9])([A-Z])", r"\\1_\\2", name)
    snake = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\\1_\\2", snake)
    return WIDGET_IO_PREFIX + snake.upper()


def route(path: str) -> str:
    """Namespaced HTTP route: "media" -> ${pyStr(id.route('media'))}."""
    return f"{ROUTE_PREFIX}/{path.lstrip('/')}"


def setting_id(name: str) -> str:
    """Namespaced ComfyUI settings key."""
    return f"{NAMESPACE}.{name}"
`
}

function render(manifest: PackManifest, python: PythonConfig): Map<string, string> {
  const files = new Map<string, string>()
  for (const name of MODULES)
    files.set(
      name,
      name === 'identity.py'
        ? identityModule(manifest, python)
        : header() + readFileSync(join(TEMPLATES, name), 'utf8'),
    )
  return files
}

function sync(root: string, check: boolean): number {
  const { manifest, python } = readPack(root)
  const pkgDir = join(root, python.package)
  if (!existsSync(join(pkgDir, '__init__.py')))
    throw new UsageError(
      `${python.package}/__init__.py not found: "python.package" must name the pack's node package.`,
    )
  const dir = join(pkgDir, python.vendor)
  const shown = relative(root, dir) || '.'
  const files = render(manifest, python)
  const stale: string[] = []
  const foreign: string[] = []

  for (const [name, text] of files) {
    const path = join(dir, name)
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (current === text) continue
    stale.push(`${shown}/${name}${current === null ? ' (missing)' : ''}`)
    if (!check) {
      mkdirSync(dir, { recursive: true })
      writeFileSync(path, text)
    }
  }
  // Leftovers: a module a previous nodekit generated is removed; anything else is not ours to
  // delete, but it doesn't belong in a generated package either.
  if (existsSync(dir))
    for (const name of readdirSync(dir)) {
      if (files.has(name) || name === '__pycache__') continue
      const path = join(dir, name)
      const ours = name.endsWith('.py') && readFileSync(path, 'utf8').includes(MARKER)
      if (ours) {
        stale.push(`${shown}/${name} (no longer generated)`)
        if (!check) rmSync(path)
      } else foreign.push(`${shown}/${name}`)
    }

  for (const f of foreign)
    console.warn(`zenkit-nodekit: ${f} is not generated; move it out of ${shown}/.`)
  if (check) {
    if (!stale.length && !foreign.length) {
      console.log(`zenkit-nodekit: ${shown}/ is up to date (nodekit ${VERSION}).`)
      return 0
    }
    for (const f of stale) console.error(`  stale: ${f}`)
    console.error('zenkit-nodekit: vendored Python is out of date. Run `zenkit-nodekit sync`.')
    return 1
  }
  console.log(
    stale.length
      ? `zenkit-nodekit: wrote ${stale.length} file(s) to ${shown}/ (nodekit ${VERSION}).`
      : `zenkit-nodekit: ${shown}/ already up to date.`,
  )
  return 0
}

function* pyFiles(dir: string, skip: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (path !== skip && entry.name !== '__pycache__') yield* pyFiles(path, skip)
    } else if (entry.name.endsWith('.py')) yield path
  }
}

/** The io type is a bare string on both sides, so a rename on one side fails silently: no widget
 *  renders and the prompt is rejected with "Required input is missing". */
function checkWidgets(root: string): number {
  const { manifest, python } = readPack(root)
  const { typeId } = makeIdentity(manifest)
  const widgetsDir = join(root, python.widgets)
  const components = new Map<string, string>()
  if (existsSync(widgetsDir))
    for (const name of readdirSync(widgetsDir).sort())
      if (name.endsWith('.vue')) components.set(typeId(name.slice(0, -4)), name)

  const declared = new Map<string, string>()
  const pkgDir = join(root, python.package)
  for (const path of [...pyFiles(pkgDir, join(pkgDir, python.vendor))].sort()) {
    const text = readFileSync(path, 'utf8')
    const at = relative(root, path)
    for (const m of text.matchAll(/widget_type\(\s*["']([A-Za-z0-9_]+)["']/g))
      declared.set(typeId(m[1]!), at)
    for (const m of text.matchAll(/inline_widget\([\s\S]*?,\s*["']([A-Z][A-Za-z0-9_]*)["']\s*\)/g))
      declared.set(typeId(m[1]!), at)
  }

  const problems: string[] = []
  for (const [key, source] of declared)
    if (!components.has(key))
      problems.push(`  ${key}: declared in ${source} but no ${python.widgets}/*.vue matches`)
  for (const [key, file] of components)
    if (!declared.has(key))
      problems.push(`  ${key}: ${python.widgets}/${file} has no node declaring it`)
  if (problems.length) {
    console.error('Widget contract mismatches:\n' + problems.join('\n'))
    return 1
  }
  const keys = [...components.keys()].sort()
  console.log(`Widget contract OK (${keys.length} widget(s)): ${keys.join(', ')}`)
  return 0
}

const USAGE = `zenkit-nodekit ${VERSION}

Usage: zenkit-nodekit <command> [--root <pack dir>]

  sync             write <python.package>/<python.vendor>/ (default nodes/_zenkit/) from pack.json
  sync --check     exit 1 if those files are stale or missing (for CI); writes nothing
  check-widgets    exit 1 if a Python widget type has no frontend/widgets/*.vue, or the reverse
`

function main(argv: string[]): number {
  const args = [...argv]
  const take = (flag: string) => {
    const i = args.indexOf(flag)
    if (i < 0) return undefined
    const [, value] = args.splice(i, 2)
    if (!value) throw new UsageError(`${flag} needs a value.`)
    return value
  }
  const flag = (name: string) => {
    const i = args.indexOf(name)
    return i >= 0 && !!args.splice(i, 1).length
  }
  if (flag('--version')) {
    console.log(VERSION)
    return 0
  }
  const help = flag('--help') || flag('-h')
  if (help || !args.length) {
    console.log(USAGE)
    return help ? 0 : 2
  }
  const root = resolve(take('--root') ?? process.cwd())
  const check = flag('--check')
  const [command, ...rest] = args
  if (rest.length) throw new UsageError(`Unexpected arguments: ${rest.join(' ')}`)
  if (command === 'sync') return sync(root, check)
  if (command === 'check-widgets' && !check) return checkWidgets(root)
  throw new UsageError(`Unknown command: ${args.join(' ')}\n\n${USAGE}`)
}

try {
  process.exitCode = main(process.argv.slice(2))
} catch (err) {
  if (!(err instanceof UsageError || err instanceof SyntaxError)) throw err
  console.error(`zenkit-nodekit: ${err.message}`)
  process.exitCode = 2
}
